Practice programs pandas

In [1]:
import pandas as pd
import numpy as np

In [5]:
#1.Create DataFrame from a dictionary
df=pd.DataFrame({'name':['ram','diya','om'],
                 'age':[20,19,21],
                 'gender':['male','female','male']})
df

   name  age  gender
0   ram   20    male
1  diya   19  female
2    om   21    male

In [14]:
#2.Rename columns of a DataFrame.
df1=df.rename(columns={'name':'fullname'})
df1

  fullname  age  gender
0      ram   20    male
1     diya   19  female
2       om   21    male

In [15]:
#3. Sort DataFrame by multiple columns
df.sort_values(by=['gender','age'])

   name  age  gender
1  diya   19  female
0   ram   20    male
2    om   21    male

In [17]:
#4.Fill missing values with forward fill method.
df2=pd.DataFrame({'A': [1, np.nan, 3], 'B': [np.nan, 5, 6]})
dff=df2.fillna(method='ffill')
dff

C:\Users\Hp EliteBook\AppData\Local\Temp\ipykernel_18228\1497722232.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dff=df2.fillna(method='ffill')

     A    B
0  1.0  NaN
1  1.0  5.0
2  3.0  6.0

In [19]:
#5.Create a new column that is sum of two existing columns.
data=pd.DataFrame({'Math': [80, 90], 'Science': [85, 95]})
data['total']=data['Math']+data['Science']
data

   Math  Science  total
0    80       85    165
1    90       95    185

In [23]:
#6.Drop duplicate rows based on one column
data=pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice'], 'Age': [25, 30, 25]})
print(data)
d=data.drop_duplicates(subset='Name')
d

    Name  Age
0  Alice   25
1    Bob   30
2  Alice   25

    Name  Age
0  Alice   25
1    Bob   30

In [25]:
#7.Filter rows where 'Name' contains the letter 'a'
data[data['Name'].str.contains('a',case=False)]

    Name  Age
0  Alice   25
2  Alice   25

In [27]:
#8. Group by a category and calculate the mean
df=pd.DataFrame({'Department': ['HR', 'IT', 'HR'], 'Salary': [50000, 60000, 55000]})
grp=df.groupby(df['Department']).mean()
grp

             Salary
Department
HR          52500.0
IT          60000.0

In [30]:
#9.Convert column datatype to integer
dff=pd.DataFrame({'Age': ['25', '30', '22']})
dff['Age'] = dff['Age'].astype(int)
dff

   Age
0   25
1   30
2   22

In [33]:
#10.Replace all 'active' values with 'enabled'
d=pd.DataFrame({'Status': ['active', 'inactive', 'active']})
d['Status'] = d['Status'].replace('active', 'enabled')
d

     Status
0   enabled
1  inactive
2   enabled

In [36]:
#11.Convert date column and extract year/month
df=pd.DataFrame({'JoinDate': ['2021-01-10', '2022-03-15']})
df['JoinDate'] = pd.to_datetime(df['JoinDate'])
df['Year'] = df['JoinDate'].dt.year
df['Month'] = df['JoinDate'].dt.month
df

    JoinDate  Year  Month
0 2021-01-10  2021      1
1 2022-03-15  2022      3